#pragma once

#include <QJsonObject>
#include <QString>
#include <QStringList>
#include <memory>

#include "include/ui/widget/json/JsonSchemaValidator.h"

namespace JsonEdit {
namespace SingBox {
// Pointers into the bundled schema (res/schema/sing-box.json), regenerated by script/gen_schema.sh.
inline constexpr auto Config = "";
inline constexpr auto Outbound = "#/$defs/Outbound";
inline constexpr auto Endpoint = "#/$defs/Endpoint";
inline constexpr auto Route = "#/$defs/RouteOptions";
inline constexpr auto Dns = "#/$defs/DNS";
} // namespace SingBox

const QJsonObject& SingBoxSchema();

// A fresh validator each call: relaxations are per-editor, so instances are never shared.
std::shared_ptr<SchemaValidator> SingBoxValidator(const QString& rootRef = {});

std::shared_ptr<SchemaValidator> SingBoxValidator(const QStringList& rootRefs);
} // namespace JsonEdit
